services:
  shopping-cart-api:
    build: .
    container_name: shopping-cart-api
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
      DB_HOST: db
      DB_NAME: shopping_cart
      DB_USER: postgres
      DB_PASSWORD: root123
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shopping-cart-network

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: shopping_cart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
    volumes:
      - shopping_cart_postgres_data:/var/lib/postgresql/data
    networks:
      - shopping-cart-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shopping_cart"]
      interval: 2s
      timeout: 5s
      retries: 15
      start_period: 10s

volumes:
  shopping_cart_postgres_data:

networks:
  shopping-cart-network:
    driver: bridge